persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi

service:
  type: ClusterIP
  port: 8081
  additionalPorts:
    - name: docker
      port: 5000
      containerPort: 5000

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

# JVM heap
install4jAddVmParams: "-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=512m"
