apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: n8n
      targetRevision: "1.8.7"
      helm:
        valueFiles:
          - $values/helm-values/n8n/values.yaml
    - repoURL: https://github.com/JewishKebab/K8Exo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
