apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Upstream Helm chart
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: "6.18.0"
      helm:
        valueFiles:
          - $values/helm-values/open-webui/values.yaml
    # Our values live in this repo
    - repoURL: https://github.com/JewishKebab/K8Exo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
