timezone: "Asia/Jerusalem"

main:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "local-path"
    mountPath: "/home/node/.n8n"

  extraEnvVars:
    N8N_BASIC_AUTH_ACTIVE: "true"
    N8N_BASIC_AUTH_USER: "admin"
    N8N_BASIC_AUTH_PASSWORD: "admin123"
    WEBHOOK_URL: "http://localhost:5678"

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"

service:
  type: ClusterIP
  port: 5678